### PR TITLE
added queryParams for list calls

### PR DESCRIPTION
**Pull request by purplecones**

### CODE REVIEW

**Comment by tmcpro** [comment]
I typically would make the callback being the last parameter since it is more intuitive. You can also create an object and pass it in for the options which might be more useful for complex options in the future. This would require us checking to see it any options was passed or not though.

For example:

``` javascript
FundAmerica.offerings.list({page: 2}, function(err, data) {
     console.log(data);
     if(err){
         console.log(err);
     }
 });
```

If you want to restructure it in another PR might be a good idea. For now im going to merge this through.

**Comment by purplecones** [comment]
I wanted to do that but had some issues down the chain where cb was `not a function` or doesn't get called at all.

**Comment by tmcpro** [comment]
@purplecones that was the "check" i was talking about. Not sure how many people use this library so its nothing crazy is needed.

**Comment by purplecones** [comment]
Check out PR https://github.com/tmcpro/fundamerica/pull/6

**Pull request merged**
