### PR TITLE
Moved callbacks to last position

### PR DESCRIPTION
**Pull request by purplecones**
@tmcpro Not sure if this is the best way to handle it. Let me know if you have other ideas.

### CODE REVIEW

**Comment by tmcpro** [comment]
havent tested it but looks good.

**Comment by purplecones** [comment]
Will you publish new version to npm?

**Comment by tmcpro** [comment]
@purplecones published under v1.0 due to major changes to functions. 

https://www.npmjs.com/package/fundamerica

**Comment by purplecones** [comment]
@tmcpro awesome, thanks!

**Pull request merged**
